### PR TITLE
git add . before committing

### PR DESCRIPTION
**Pull request by rohitpaulk**

### CODE REVIEW

**Comment by rohitpaulk** [comment]
@nikandfor could you take over this PR? (I haven't verified that it works + not sure if the error handling is correct). Based on this user report: 

Screenshot 2022-11-23 at 19 12 06

**Comment by nikandfor** [comment]
I tried to run it, and it worked. And error handling is pretty smart. So I think we can merge it.

Yet error handling when running command through the shell is hard and fragile. And I would used https://github.com/go-git/go-git instead of command line git.

**Comment by nikandfor** [comment]
So are we merge it for now?

**Comment by rohitpaulk** [comment]
Yep, sorry thought the merge conflict wasn’t resolved yet - merging

**Pull request merged**
